### PR TITLE
EPF Message function using DB

### PR DESCRIPTION
**Pull request by valid22**

### CODE REVIEW

**Comment by TunnelBlanket** [comment]
I'll think about merging this, but this would probably be better off as a plugin.

**Comment by valid22** [comment]
Ok, But , go on!

**Comment by lake-icp** [comment]
Who even reads EPF messages these days?

**Comment by valid22** [comment]
Everyone except u does.

**Comment by Elixur** [comment]
Lake-icp if a CPPS wanted working agents 100% it would also require EPF messages.

**Comment by TunnelBlanket** [comment]
CPPS owners can implement this themselves.

**Pull request closed without merging**
